# For full config options, check the docs:
#    docs.serverless.com
service: status-update-db
app: status-update
org: newellwm

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  environment:
    TASK_TABLE: ${self:custom.prefix}-task
    TASK_TABLE_USER_INDEX: username-title-index
    STATUS_TABLE: ${self:custom.prefix}-status
custom:
  prefix: ${self:service}-${self:provider.stage}
resources:
  Resources:
    taskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TASK_TABLE}
        AttributeDefinitions:
          - AttributeName: category
            AttributeType: S
          - AttributeName: title
            AttributeType: S
        KeySchema:
          - AttributeName: category
            KeyType: HASH
          - AttributeName: title
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.TASK_TABLE_USER_INDEX}
            KeySchema:
              - AttributeName: username
                KeyType: HASH
              - AttributeName: title
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    statusTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.STATUS_TABLE}
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
          - AttributeName: datetask
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
          - AttributeName: datetask
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: task-postedOn-index
            KeySchema:
              - AttributeName: task
                KeyType: HASH
              - AttributeName: postedOn
                KeyType: RANGE
            Projection:
              ProjectionType: KEYS_ONLY
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
