functions:
  create:
    handler: tasks.create
    events:
      - http:
          path: tasks
          method: post
          cors: true
          response:
            statusCodes:
              201:
                pattern: ''
  getByCategory: tasks.getByCategory
    handler:
    events:
      - http:
          path: category/{category}/tasks
          method: get
          cors: true
          request:
            parameters:
              paths:
                category: true
  getByUser: tasks.getByUser
    handler:
    events:
      - http:
          path: /users/{id}/tasks
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
  update: tasks.update
    handler:
    events:
      - http:
          path: tasks/category/{category}/title/{title}
          method: patch
          cors: true
          request:
            parameters:
              paths:
                category: true
                title: true
  replace:
    handler: tasks.replace
    events:
      - http:
          path: tasks/category/{category}/title/{title}
          method: put
          cors: true
          request:
            parameters:
              paths:
                category: true
                title: true
  delete:
    handler: tasks.remove
    events:
      - http:
          path: tasks/category/{category}/title/{title}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                category: true
                title: true