service: lambda
app: status-update
org: newellwm

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  prune: # automatically prune old lambda versions
    automatic: true
    number: 3

plugins:
  - serverless-webpack
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs12.x
  frameworkVersion: ‘1.64.1’
  versionFunctions: false
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  apiGateway:
    minimumCompressionSize: 1024 *# Enable gzip compression for responses > 1 KB
  environment:
    DEBUG: "*"
    NODE_ENV: ${self:provider.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  tracing:
    lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:*" # replace with cloud formation input for the dynamos

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello
